osism/defaults

- all/kolla.yml
> kolla: do not become root by default

- all/images-ceph.yml
> Add ceph images

- all/001-kolla-defaults.yml
> Add upstream kolla defaults

- all/generic.yml
- all/kolla.yml
> Remove dup operator parameters

- all/003-kolla-overlays.yml
> Add kolla overlays

- all/003-kolla-overlays.yml
> Add enable_qinling to kolla overlays

- all/003-kolla-overlays.yml
> Add enable_searchlight to kolla overlays

- all/003-kolla-overlays.yml
> Add enable_horizon_* to kolla overlays

- all/002-images-kolla.yml
> kolla: fix mariadb image >= wallaby

- all/003-kolla-overlays.yml
> kolla: set ceph default user & pool name for glance

- all/099-infrastructure.yml
Signed-off-by: Ferenc Géczi <geczi@univention.de>
> Add openldap defaults

- all/003-kolla-overlays.yml
> kolla: enable prometheus by default

- all/099-infrastructure.yml
> Add client versions

- manager.yml
> Remove maas arguments

- all/001-kolla-defaults.yml
> kolla: comment docker defaults

- all/002-images-ceph.yml
- all/002-images-kolla.yml
> Add client images to ceph-ansible & kolla-ansible defaults

- all/000-registries.yml
> Add default registries

- all/099-infrastructure.yml
> Add UMC/UDM host arguments

- all/099-infrastructure.yml
> Add virtualbmc_host

- all/002-images-kolla.yml
- all/099-kolla.yml
> kolla: use prometheus-v2-server image if prometheus_use_v1 is not set

- all/099-infrastructure.yml
> Set nexus host

- all/099-interfaces.yml
> Set console_interface & management_interface

- all/001-kolla-defaults.yml
> Sync kolla defaults

- all/099-generic.yml
> Add configuration_directory

- manager.yml
> manager: add internal_interface

- all/099-generic.yml
> Add docker_registry_nexus

- all/099-generic.yml
> Add docker_registry_netbox

- all/099-ceph.yml
> Add common ceph defaults

- all/099-generic.yml
> Install docker-compose from package by default

- all/099-ceph.yml
> Use rgw_create_pools for the moment

- all/099-infrastructure.yml
> Add treafik host

- all/099-kolla.yml
> kolla: set glance_enable_rolling_upgrade

- .github/workflows/check-yaml-syntax.yml
partly: osism/issues#85
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
> github: run branch builds on main only

- all/099-infrastructure.yml
> Add dnsdist_host

- all/001-kolla-defaults.yml
> Sync 001-kolla-defaults.yml with stable/wallaby

- all/000-registries.yml
- all/099-infrastructure.yml
> Add cgit parameters

- all/003-kolla-overlays.yml
> Use bool instead of string

- all/001-kolla-defaults.yml
> Adapt kolla defaults for Xena

- all/000-registries.yml
- manager.yml
> Remove awx

- all/001-kolla-defaults.yml
- all/002-images-kolla.yml
> Add vars for prometheus libvirt exporter

- all/002-images-kolla.yml
> Fix missing / in -prometheus_libvirt_exporter_image

- all/002-images-kolla.yml
> Fix double pipe

- .zuul.yaml
> Drop merge-mode: squash-merge in .zuul.yaml

- all/000-registries.yml
> Add docker_registry_patchman

- all/099-kolla.yml
> kolla: enable mariadb backup by default

- all/002-images-kolla.yml
> Add ironic_inspector_tag

- all/000-registries.yml
- all/099-infrastructure.yml
partly osism/issues#217
Signed-off-by: Tim Beermann <beermann@osism.tech>
> add squid parameters

- all/001-kolla-defaults.yml
> Adapt kolla defaults for Yoga

- all/001-kolla-defaults.yml
> kolla: re-add endpoint parameters

- all/001-kolla-defaults.yml
> kolla: add missing enable_kibana_external

- all/099-kolla.yml
5d/7d soft/hard-delete
Closes osism/issues#272
> kolla: enable the es curator by default

- all/099-kolla.yml
> kolla: enable designate & octavia by default

- all/099-ceph.yml
> Remove docker_registry from ceph

- all/000-registries.yml
> Add missing docker_registry_phpmyadmin

- all/000-registries.yml
> Use nexus image from quay.io

- all/001-kolla-defaults.yml
> Update kolla defaults for Zed release

- all/099-ceph.yml
> Add variables required by ceph-validate role

- all/002-images-kolla.yml
> kolla: add opensearch images

- all/099-kolla.yml
> kolla: add enable_common

- all/001-kolla-defaults.yml
> kolla: add defaults for new datadir volumes

- all/099-kolla.yml
Default location is not writable.
> Set octavia_certs_work_dir = /share

- all/099-kolla.yml
Related to:
- https://github.com/SovereignCloudStack/issues/issues/293
> Modify ansible default to use authorization code.

- all/001-kolla-defaults.yml
- all/099-kolla.yml
This will also revert 6ed9f46f27e2b736571a723887105cb02cae7243.
> kolla: use opensearch osprofiler parameters

- all/099-kolla.yml
> kolla: remove docker_restart_policy_retry

- all/001-kolla-defaults.yml
This reverts 93b220e3ec11392e36e6277886e2149b8dd094ec.
> Sync kolla defaults with upstream (stable/2023.1)

- all/099-kolla.yml
Part of https://github.com/SovereignCloudStack/issues/issues/412
> Move the testbed federation config to the production repositories

- all/099-generic.yml
- releasenotes/notes/new-default-for-hosts-type-70057feded5fbb27.yaml
> Set hosts_type = template

- all/099-kolla.yml
Related to osism/container-image-kolla-ansible#577
> Remove nova & cinder ceph_keyring parameters

- all/002-images-kolla.yml
> kolla: add skyline_console tag

- all/099-generic.yml
So we can remove these defaults from the cookiecutter and so on.
> Add dotfiles defaults

- all/099-infrastructure.yml
> Remove openldap related parameters

- all/099-kolla.yml
> kolla: do not enable the jobboard by default

- all/099-k3s.yml
https://github.com/techno-tim/k3s-ansible/releases/tag/v1.29.2%2Bk3s1%2Btt1
> Use k3s-ansible v1.29.2+k3s1

- all/099-infrastructure.yml
Related PRs
- https://github.com/osism/ansible-playbooks/pull/420
- https://github.com/osism/ansible-collection-services/pull/1434
SCS issue: https://github.com/SovereignCloudStack/issues/issues/576
> Add kubernetes_monitoring defaults

- all/099-kolla.yml
This reverts commit 5fd1b29bfb09b8f443a31b7af44f4ebf42707819.
> Revert "kolla: enable the prometheus push gateway by default"

- all/099-k3s.yml
> Add missing cluster_cidr parameter

- all/000-registries.yml
> Remove openstack-health-monitor parameter

- all/099-kolla.yml
> kolla: disable deprecation warnings in API services

- all/000-registries.yml
> Add docker_registry_pgautoupgrade

- ansible.cfg
> Set interpreter_python = auto_silent in ansible.cfg

- rook-mds.yml
- rook-mgr.yml
- rook-mon.yml
- rook-osd.yml
- rook-rgw.yml
Related to https://github.com/osism/ansible-playbooks/pull/504
> Add rook node labels via kubernetes-label-nodes play

- compute.yml
- control.yml
- k3s_master.yml
- k3s_node.yml
- manager.yml
- network.yml
Related to 789cefa27ae111e87714a20ee3e508188869899e
Required because of https://github.com/osism/ansible-playbooks/pull/504
> Add missing _ to k3s_add_labels parameters

- all/099-ceph.yml
- all/099-interfaces.yml
I created this PR because validations failed without the definition of these keys.
This PR adds defaults for that.
> set defaults to reduce problems with ceph validations

- all/099-ceph.yml
* cephfs_pool_default_rule_name
* openstack_pool_default_rule_name
> ceph: add parameters to set the default rule name

- all/002-images-kolla.yml
> kolla: add neutron-ovn-vpn-agent image

- all/099-kolla.yml
Related to d8057b11fa485b04c4329e45bcc10b5e15ba6a86
> Fix kolla defaults for 2024.1

- all/099-k3s.yml
This reverts commit 2f0ba19341df5b8289f525bb52a85434427fee7f.
> Revert "Fix default value for k3s_node_ip"
