osism/defaults

all/099-generic.yml

Set rsyslog_fluentd_host to internal_address by default

---

all/001-kolla-defaults.yml

kolla: set default value when horizon_enable_tls_backend is not set

---

all/099-kolla.yml

kolla: enable neutron port forwarding by default

---

all/099-kolla.yml

Mitigating the log4j Vulnerability (CVE-2021-44228/CVE-2021-45046)

Add es_java_opts

---

all/002-images-kolla.yml

The version of Kolla to be used is not set via the defaults
and leads to problems when creating the inventory if it is
set here.
The active Kolla version is made available to the Inventory
Reconciler via the interface volume from the Kolla Ansible container.

Remove kolla_image_version

---

all/003-kolla-overlays.yml

In python-osism the Ironic notifications are used
regardless of whether Ceilometer is available or
not. This is necessary to update the system states
in the Netbox and to transfer the results of the
introspection.

Always enable ironic notifications

---

all/099-infrastructure.yml

The versions of the clients are always dependent on
the ceph/kolla-ansible containers used. They are
provided via /interface/versions.
Otherwise, the default that is defined in the respective
role should be used.

Remove openstackclient/cephclient_version parameters

---

all/099-kolla.yml

Currently, Grafana is explicitly activated via the
configuration repository. By default it is only
activated if Monasca is activated.
From now on, Grafana is always activated by default
and must be explicitly deactivated in the configuration
repository if required.

kolla: enable grafana by default

---

all/099-generic.yml

The ModemManager.service is activated when using the default
Ubuntu images. It is usually not needed.

Disable ModemManager.service

---

all/002-images-kolla.yml
all/099-kolla.yml

This avoids that docker_registry is overwritten. It's quay.io by default.
Related to osism/issues#211

Use docker_registry_kolla

---

all/001-kolla-defaults.yml

The `prometheus_openstack_exporter_compute_api_version` variable was
introduced by [0] and backported into stable releases.
[0] https://review.opendev.org/c/openstack/kolla-ansible/+/828902
Fixes: osism/issues#256

Add new kolla-ansible variable

---

all/099-kolla.yml

The used check does not work in the ceilometer-central container. It probably depends
on the underlying operating system.
Closes osism/issues#231

kolla: disable ceilometer-central healthcheck

---

all/001-kolla-defaults.yml

It is still needed for xena and older releases.

kolla: add missing enable_ironic_ipxe parameter

---

all/099-kolla.yml

The used check does not work in the gnocchi-statsd container.
Closes osism/issues#288

kolla: disable gnocchi-statsd healthcheck (#82)

---

all/001-kolla-defaults.yml

Closes osism/cloud-in-a-box#14

Add missing external_ceph_always_copy_cinder_keyring

---

all/099-generic.yml

Install python-is-python3 by default

---

all/099-ceph.yml

The firewall tasks in ceph-infra are only available for SUSE and RedHat based distributions. Therefore, we can also deactivate and skip this by default.

ceph: set configure_firewall = false

---

all/001-kolla-defaults.yml

In [0] om_enable_rabbitmq_high_availability was added as a new variable, add it to our kolla defaults.
[0] https://review.opendev.org/c/openstack/kolla-ansible/+/870494

Add new kolla option for stable branches

---

manager.yml

The cockpit role was removed some time ago. This is a leftover.

manager: remove cockpit_host

---

all/000-registries.yml

The osism/dnsdist image is only available on quay.io.

Set docker_registry_dnsdist=quay.io

---

all/000-registries.yml

Information from zuul-announce@lists.zuul-ci.org from 2023-04-27 22:14 CEST
depends osism/release#878
Signed-off-by: Tim Beermann <beermann@osism.tech>

Registries: Change zuul registry to quay.io

---

all/099-kolla.yml

This avoids conflicts with elasticsearch.

kolla: use redis as backend for osprofiler

---

all/099-kolla.yml

Kolla no longer deploys chrony, drop the variable from its defaults.

Drop enable_chrony from kolla defaults

---

all/099-generic.yml

Add nvme-cli and lsscsi as mentioned in https://github.com/osism/issues/issues/634
Signed-off-by: Paul-Philipp Kuschy <kuschy@osism.tech>

Add lsscsi + nvme-cli to required_packages_default

---

all/099-kolla.yml

Required to be backward compatible.

Add enable_skydive parameter

---

all/099-kolla.yml

Required to be backward compatible.

Add enable_ironic_dnsmasq parameter

---

all/099-kolla.yml

Required for our custom rabbitmq datadir volume.

Add rabbitmq_datadir_volume

---

all/001-kolla-defaults.yml

Have been introduced through a backport on kolla-ansibl@stable/2023.1 and are therefore not yet there.

kolla: add missing ironic interface parameters

---

all/001-kolla-defaults.yml

Required by OpenStack Zed & OpenStack 2023.1.

Add skyline_internal_fqdn & skyline_external_fqdn

---

all/099-generic.yml

Those packages are installed by default when working the the Ubuntu ISO installer and should be removed by default.

Remove some packages by default

---

all/099-k3s.yml

This has to be set now by default (it's the default in k3s-ansible also, the cilium_bgp parameter has to be part of the group_vars).

k3s: add cilium_bgp parameter

---

all/099-interfaces.yml

This can simplify the osism.commons.hosts template.

Set hosts_interface to internal_interface by default

---

all/099-generic.yml

This is necessary so that multiple different distributions are supported by default without further customisation.
The default in osism.commons.repository for Ubuntu corresponds exactly to these entries that will be removed. The default behaviour does not change when deployed on Ubuntu.

Use default repositories from osism.commons.repository

---

all/099-k3s.yml

This PR adds the k3s monitoring arguments to the k3s servers. 
The k3s configuration has been tested with testbed deployment. In addition, this configuration is already a part SCS observability quickstart guide for k3s monitoring https://github.com/SovereignCloudStack/k8s-observability/pull/49
Open question:
- Should be `k3s_monitoring: true` default?
Related to: https://github.com/SovereignCloudStack/issues/issues/576

Add k3s monitoring defaults

---

all/099-generic.yml

This is necessary so that multiple different distributions are supported by default without further customisation.
The new defaults in osism.commons.cleanup for Ubuntu corresponds exactly to these entries that will be removed. The default behaviour does not change when deployed on Ubuntu.
Related to osism/ansible-collection-commons#633

Use default cleanups from osism.commons.cleanup

---

all/099-ceph.yml

Set ceph dashboard standby to error with status 404
Part of https://github.com/osism/issues/issues/1013

Set ceph dashboard standby behaviour

---

all/099-kolla.yml

node_config is set to the correct environment by the run.sh script in the kolla-ansible container. This is important when working with sub-environments. Therefore node_custom_config must access node_config as otherwise the correct sub environment is not used.

kolla: fix node_custom_config

---

all/099-generic.yml

The osism user is used on osism/node-image. It shoue be removed after the initial bootstrap. So that you don't have to do this manually, it will be removed by default from now on.

Delete the osism user by default

---

all/099-k3s.yml

The "Copy vip manifest to first master" task is always executed and requires the kube_vip_tag_version parameter.
Related to 40e79118629bf2775a45bb9767afa74ed9fddc00

Re-add the kube_vip_tag_version parameter

---

all/099-infrastructure.yml

Do not bind Nexus proxy ports by default on 0.0.0.0.

Add nexus_bind_host parameter

---

all/099-ceph.yml

We do not support podman at the moment. Always use docker as container binary and do not auto detect if podman is usable.

ceph: always use docker as container binary

---

all/099-ceph.yml

This reverts commit 63bf278b1aa0fb5af9eade2c94f071d3c8100059.
We add a patch to osism/container-image-ceph-ansible to modify container_binary.yml. There are a lot of "tasks_from: container_binary.yml" in ceph-ansible.

Revert "ceph: always use docker as container binary (#218)"

---

all/001-kolla-defaults.yml

I think it's time to activate the quorum queues. 
I also think 
- it would be good to point out to the OSISM users in the release letter that this is now the default.
- it would be very useful if we could migrate the existing queues without API downtime using a migration routine.
(something like: create a temporary queue, switch Exchange to it, delete the old queue after it has emptied, create a new queue, switch Exchange to the new queue)

Make quorum queues the default

---

all/099-k3s.yml

* cilium_tag: v1.16.4
* k3s_version: v1.30.6+k3s1
* kube_vip_tag_version: v0.8.7

k3s: update versions

---

all/099-kolla.yml

K8s volumes should be monitored from inside the cluster. It cannot be done in a meaningful way by the node-exporter.
If not excluded they are shown in `node_filesystem_device_error` as erroneous.

Exclude k8s volumes from node-exporter

---

all/099-kolla.yml

The ironic_prometheus_exporter is broken right now and cannot be scraped. The error is in the ironic-conductor ([1]) while fetching the metrics.
[1]
2024-12-07 10:18:15.321 7 ERROR ironic.conductor.manager [-] An unknown error occurred while attempting to collect sensor data from within the conductor. Error: Metrics action is not supported. You may need to adjust the [metrics] section in ironic.conf.: ironic_lib.exception.MetricsNotSupported: Metrics action is not supported. You may need to adjust the [metrics] section in iro nic.conf.
2024-12-07 10:18:15.321 7 ERROR ironic.conductor.manager Traceback (most recent call last):
2024-12-07 10:18:15.321 7 ERROR ironic.conductor.manager   File "/var/lib/kolla/venv/lib/python3.10/site-packages/ironic/conductor/manager.py", line 2681, in …

Disable ironic_prometheus_exporter (#2557)

---

all/099-ceph.yml

With the openstack_pool_default_pg_autoscale_mode parameter it is possible to define the default value for the pg_autoscale_mode of the OpenStack pools.

ceph: add openstack_pool_default_pg_autoscale_mode parameter

---

all/099-k3s.yml

https://docs.k3s.io/installation/registry-mirror

k3s: enable distributed OCI registry mirror

---

all/099-k3s.yml

The cilium CLI is pre-installed in osism/osism-kubernetes container image.

k3s: do not manage cilium CLI with k3s-ansible

---

all/001-kolla-defaults.yml
all/099-interfaces.yml

Changes default network interface configuration across kolla defaults and interface definitions to use loopback0 instead of eth0.

Update network interface from eth0 to loopback0
